Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/kpi/views.py", line 11, in index
    return render(request, 'my-cleaning-app/build/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/env/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/env/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/env/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my-cleaning-app/build/index.html
"GET / HTTP/1.1" 500 77161
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/kpi/views.py", line 11, in index
    return render(request, 'my-cleaning-app/build/index.html')
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my-cleaning-app/build/index.html
"GET / HTTP/1.1" 500 76407
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/kpi/views.py", line 11, in index
    return render(request, 'my-cleaning-app/build/index.html')
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my-cleaning-app/build/index.html
"GET / HTTP/1.1" 500 76469
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/kpi/views.py", line 11, in index
    return render(request, 'my-cleaning-app/build/index.html')
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my-cleaning-app/build/index.html
"GET / HTTP/1.1" 500 76597
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/kpi/views.py", line 11, in index
    return render(request, 'my-cleaning-app/build/index.html')
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 23, in get_template
    contents = self.get_contents(origin)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 26, in get_contents
    return origin.loader.get_contents(origin)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/loaders/filesystem.py", line 22, in get_contents
    with open(origin.name, encoding=self.engine.file_charset) as fp:
NotADirectoryError: [Errno 20] Not a directory: '/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/my-cleaning-app/build/index.html/my-cleaning-app/build/index.html'
"GET / HTTP/1.1" 500 106575
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/kpi/views.py", line 11, in index
    return render(request, 'my-cleaning-app/build/index.html')
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nathanserfaty/Desktop/Saas_data_analyser_cleaner/kpi_dashboard/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my-cleaning-app/build/index.html
"GET / HTTP/1.1" 500 76407
